
CREATE TABLE IF NOT EXISTS courses
(
    id_course   INTEGER NOT NULL auto_increment,
    name        VARCHAR(50)  not null,
    description VARCHAR(250) not null,
    CONSTRAINT courses_pk
    PRIMARY KEY (id_course)
    );

CREATE TABLE IF NOT EXISTS students
(
    id_student INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(20) NOT NULL,
    lastname   VARCHAR(20) NOT NULL,
    id_course  INTEGER     NOT NULL,
    CONSTRAINT students_pk
        PRIMARY KEY (id_student),
    CONSTRAINT students_course_fk
        FOREIGN KEY (id_course) REFERENCES courses
);
create table IF NOT EXISTS results
(
    id_student INTEGER NOT NULL,
    id_course  INTEGER NOT NULL,
    score      INTEGER NOT NULL,
        CONSTRAINT course_fk
        FOREIGN KEY (id_course) REFERENCES courses,
        CONSTRAINT student_fk
        FOREIGN KEY (id_student) REFERENCES students
);
CREATE INDEX IF NOT EXISTS lastname_index
    ON students(lastname);